#!/bin/bash
if [[ -z $1 ]]
then
	echo -e "\033[31mOut of map's name.\033[0m"
	exit
else
	if [[ $1 = "-m" || $1 = "-f" || $1 = "-v" ]]
	then
		if [[ $1 = "-m" ]]
		then
			echo -e "\033[32m--------------------------------------------------"
			grep "#Here is the number of lines required: " maps/$2 | head -1
			echo -n "#Here is the number of lines: "
			(time ./lem_in < $2) 1>1 2>>1
			grep -c "L" 1
			grep "user" 1 | awk -F " " '{printf "#Time: %s\n", $2}'
			echo -e "--------------------------------------------------\033[0m"
			rm 1
		else
			if [[ $1 = "-v" ]]
			then
				./lem_in < $2 | ./visu_hex
			else
				echo -e "\033[32m--------------------------------------------------"
				echo "Test for flow-one:"
				./maps/generator --flow-one > maps/map_test
				grep "#Here is the number of lines required: " maps/map_test | head -1
				echo -n "#Here is the number of lines: "
				(time ./lem_in < maps/map_test) 1>1 2>>1
				grep -c "L" 1
				grep "user" 1 | awk -F " " '{printf "#Time: %s\n", $2}'
				echo -e "\033[33m--------------------------------------------------"
				echo "Test for flow-ten:"
				./maps/generator --flow-ten > maps/map_test
				grep "#Here is the number of lines required: " maps/map_test | head -1
				echo -n "#Here is the number of lines: "
				(time ./lem_in < maps/map_test) 1>1 2>>1
				grep -c "L" 1
				grep "user" 1 | awk -F " " '{printf "#Time: %s\n", $2}'
				echo -e "\033[34m--------------------------------------------------"
				echo "Test for flow-thousand:"
				./maps/generator --flow-thousand > maps/map_test
				grep "#Here is the number of lines required: " maps/map_test | head -1
				echo -n "#Here is the number of lines: "
				(time ./lem_in < maps/map_test) 1>1 2>>1
				grep -c "L" 1
				grep "user" 1 | awk -F " " '{printf "#Time: %s\n", $2}'
				echo -e "\033[31m--------------------------------------------------"
				echo "Test for big:"
				./maps/generator --big > maps/map_test
				grep "#Here is the number of lines required: " maps/map_test | head -1
				echo -n "#Here is the number of lines: "
				(time ./lem_in < maps/map_test) 1>1 2>>1
				grep -c "L" 1
				grep "user" 1 | awk -F " " '{printf "#Time: %s\n", $2}'
				echo -e "\033[36m--------------------------------------------------"
				echo "Test for big-superposition:"
				./maps/generator --big-superposition > maps/map_test
				grep "#Here is the number of lines required: " maps/map_test | head -1
				echo -n "#Here is the number of lines: "
				(time ./lem_in < maps/map_test) 1>1 2>>1
				grep -c "L" 1
				grep "user" 1 | awk -F " " '{printf "#Time: %s\n", $2}'
				echo -e "--------------------------------------------------\033[0m"
				rm 1 maps/map_test
			fi
		fi
		exit
	fi
	if [[ $1 = "one" || $1 = "1" ]]
	then
		echo -e "\033[32m--------------------------------------------------"
		./maps/generator --flow-one > maps/map_test
	else
		if [[ $1 = "ten" || $1 = 10 ]]
		then
			echo -e "\033[33m--------------------------------------------------"
			./maps/generator --flow-ten > maps/map_test
		else
			if [[ $1 = "thousand" || $1 = "1000" ]]
			then
				echo -e "\033[34m--------------------------------------------------"
				./maps/generator --flow-thousand > maps/map_test
			else
				if [[ $1 = "big-s" ]]
				then
					echo -e "\033[36m--------------------------------------------------"
					./maps/generator --big-superposition > maps/map_test
				else
					if [[ $1 = "big" ]]
					then
						echo -e "\033[31m--------------------------------------------------"
						./maps/generator --big > maps/map_test
					else
						echo -e "\033[32m--------------------------------------------------"
						if [[ $1 = "help" ]]
						then
							./maps/generator --help
							exit
						else
							./maps/generator --$1 > maps/map_test
						fi
					fi
				fi
			fi
		fi
	fi
fi
grep "#Here is the number of lines required: " maps/map_test | head -1
echo -n "#Here is the number of lines: "
(time ./lem_in < maps/map_test) 1>1 2>>1
grep -c "L" 1
grep "user" 1 | awk -F " " '{printf "#Time: %s\n", $2}'
rm 1 maps/map_test
echo -e "--------------------------------------------------\033[0m"
